---
version: 0.2
env:
  secrets-manager:
    artifactory_username : artifactory-codepipeline-credentials:username
    artifactory_password : artifactory-codepipeline-credentials:password
    artifactory_url : artifactory-codepipeline-credentials:url
phases:
  install:
    commands:
      - printenv
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
  pre_build:
      commands:
        - TAG="$CODEBUILD_RESOLVED_SOURCE_VERSION"
        - ls -ltr
        - echo $artifactory_url
        - sed -i "s|<USERNAME>|$artifactory_username|g" ./app/requirements.txt 
        - sed -i "s|<PASSWORD>|$artifactory_password|g" ./app/requirements.txt 
        - sed -i "s|<URL>|$artifactory_url|g" app/requirements.txt 
        - cat app/requirements.txt
        #- docker login $artifactory_url:80 -u $artifactory_username -p $artifactory_password
  build:
    commands:
      - docker build --tag $artifactory_url:80/docker/sample-application .
      - helm package ./sample-helm-chart
      - mkdir package-to-upload && mv *.tgz ./packge-to-upload
      - helm repo index ./package-to-upload --url http://$artifactory_url/artifactory/helm/sample-helm-chart/

  post_build:
    commands:
      #- docker push $REPOSITORY_URI:$TAG
      - curl -u $artifactory_username:$artifactory_password -T package-to-upload/ "http://$artifactory_url/artifactory/helm/sample-helm-chart"
artifacts:
  files: build.json